### ISSUE TITLE
build on Ubuntu 14.04 issue

### ISSUE THREAD

**Issue by petrushinvs** [joyrex2001/grpc-perl#1]
Hello, there is an issue when build on Ubuntu 14.04

/usr/bin/perl /usr/share/perl/5.18/ExtUtils/xsubpp  -typemap /usr/share/perl/5.18/ExtUtils/typemap -typemap typemap  Grpc.xs > Grpc.xsc && mv Grpc.xsc Grpc.c
Please specify prototyping behavior for Grpc.xs (see perlxs manual)
cc -c  -I. -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fstack-protector -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"0.1\" -DXS_VERSION=\"0.1\" -fPIC "-I/usr/lib/perl/5.18/CORE"   Grpc.c
./ext/call.xs: In function ‘XS_Grpc__XS__Call_startBatch’:
./ext/call.xs:94:49: error: ‘struct <anonymous>’ has no member named ‘maybe_compression_level’
           ops[op_num].data.send_initial_metadata.maybe_compression_level.is_set=0;
                                                 ^
./ext/constants.xs: In function ‘XS_Grpc__XS__Constants_CHANNEL_FATAL_FAILURE’:
./ext/constants.xs:244:14: error: ‘GRPC_CHANNEL_SHUTDOWN’ undeclared (first use in this function)
     RETVAL = GRPC_CHANNEL_SHUTDOWN;
              ^
./ext/constants.xs:244:14: note: each undeclared identifier is reported only once for each function it appears in

**Comment by joyrex2001** [comment]
Can you confirm the module is linked against the 1.0 version of the grpc library?

**Comment by slanning** [comment]
I can confirm that on Ubuntu 17.04 (Zesty) libgrpc is still too old (0.12) and removing the package and building 1.0.x from source allowed the Perl module to build (1.4.x gives new errors).

It's not very related, but one of the test files mysteriously fails:
in t/10-base_stub.t the two use_ok actually pass,
but the call to $stub->_simpleRequest calls $call->start
calls $self->{_call}->startBatch and I guess a croak must happen there
though the error isn't output. I've paused at that point.

**Comment by joyrex2001** [comment]
Closing due to age.
